### ISSUE TITLE
Could not find member 'convertFromStringInterpolationSegment'

### ISSUE THREAD

**Issue by udondan** [ijoshsmith/swift-threading#2]
Should this be still working in current Xcode (6.1.1)?

I get the error message `Could not find member 'convertFromStringInterpolationSegment'`.

![bildschirmfoto 2015-01-29 um 05 43 31](https://cloud.githubusercontent.com/assets/6443408/5952553/d1a39804-a779-11e4-9a00-15b219cf5461.png)

**Comment by ijoshsmith** [comment]
That is very odd. The Swift compiler seems to be getting confused by your code, though I can't say why or how to fix it. Perhaps file a radar so Apple is aware of the issue?

**Comment by udondan** [comment]
Is this only happening for me? Is it working on your end with Xcode 6.1.1? I only wrote the expression in multiple lines, to visualize the two separate compiler messages in the screenshot. I also tried to replace the operator, since it looked like it was caused by the tilde. But I get the exact same result for every operator I set up.
