### ISSUE TITLE
First infix operator function always called, even when arguments in Xcode 7.2

### ISSUE THREAD

**Issue by lesleylawren** [ijoshsmith/swift-threading#4]
Hi, Love your code bit!  

REPO
I could be messing something up, but on a clean install and run of your program in Xcode 7.2 on my mac, I end up with output with the line '[main] sum = ()'  

EXPECTED
Instead of '[main] sum = ()' I should see '[main] sum = 49995000'

PROPOSED SOLUTION
On further investigation, it appears that the first infix function is always called (and the second one never is) - so the argument from the backgroundClosure is never passed to the mainClosure.  When I commented out the first infix function in Threading.swift, then I was able to have the output with [main] sum = 49995000.  That second function, since it is set up with generics does completely fine with no arguments as well so you might be able to completely do away with the first function.

**Comment by ijoshsmith** [comment]
Thanks Lesley! Your suggested fix worked out great.

**Comment by lesleylawren** [comment]
Great news!
